### ISSUE TITLE
6주차 수행목표

### ISSUE THREAD

**Issue by yummygyudon** [ToBeMaster-JAVA/Standard-JAVA-Basic#8]
### 1. 교재
 : **「Chapter 9. java.lang패키지와 유용한 클래스」**
#### 기간 : _2022.01.29 ~ 2022.02.04_

**＊방법은 이전 주와 동일** 

</br>

### 2. 깜지
- A4 2장 (4쪽) 분량 _ "**객체지향(chap.6 ~ chap.7) 개념**" 정리
- 작성 : **`Google Docs`** 에 작성하고 본 이슈 댓글에 ***링크 기재***

**Comment by lemon0913** [comment]
https://docs.google.com/document/d/1FB3eTE4chbvRa27hJ0O0vH-_iwDC4JvtYzdJX75WWRY/edit

**Comment by yummygyudon** [comment]
https://docs.google.com/document/d/1V_iWwg-Y9PEn_8qWGnErZYuCTkWlYe4iqGmXN4Yaeio/edit?usp=sharing

아 정리에 소질이 없다는 것을 느끼게 되었습니다..🤣

**Comment by kcho32** [comment]
https://docs.google.com/document/d/1l0bwgjm8dspjNXgKHHabbMpX4dNtNeRVszRGlHgZsCw/edit?usp=sharing

**Comment by 01stone** [comment]
https://docs.google.com/document/d/1Hvbe9JM5gXNwo0WhpwogiCBSRTBPinPDR8hKotNs3hA/edit

**Comment by red-Pen9uin** [comment]
https://docs.google.com/document/d/1-S5ZsyjOkbvfuUY7YA4Wv2ASaYhBitgVLJbGFulw3Dg/edit?usp=sharing
정리.. 미완입니다...😅

**Comment by chaesuhyeon** [comment]
https://docs.google.com/document/d/1UqC1L34-sLAXIrfTIehLD2VbUKRzDs0xPt5KygJ1qWY/edit?usp=sharing

**Comment by hanbikimm** [comment]
https://github.com/ToBeMaster-JAVA/Standard-JAVA-Basic/blob/hanbikimm/hanbikimm/summaries/Chapter_6.md
